### ISSUE TITLE
Track files and their licenses

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/kia-takatu-a-matihiko#34]
Should track the following information:

### File
- Filename
- Location of file (either in repo or not)
- Related license

### License
- Name
- URL

## Tasks
- [x] Setup basic application.
- [x] Setup admin.
- [x] Use django-tables2 and django-filter for better table management.
- [x] Load standard licences from repo.
